# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviewViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'Alamofire', '~> 4.4'
   pod 'SDWebImage', '~> 4.0'
   pod 'DropDown'
   pod 'SVProgressHUD'
  # Pods for MoviewViewer

end
